#!/usr/bin/env python3
"""Flatten one OKF tree of this bundle into a single Markdown digest.

Purpose: sync the MAGI common spec to LLMs that cannot read the repository
(chat UIs, one-shot prompts). Agents with repo access should read the bundle
directly instead.

The digest is written to stdout so nothing is committed by default:

    python scripts/okf_export.py                 # system/ tree (default)
    python scripts/okf_export.py --tree _lilith_safe
    python scripts/okf_export.py > /tmp/magi-spec.md

The LILITH contamination boundary still holds: exactly one tree is exported
per run, and a doc whose ``lilith_safe`` flag disagrees with the tree it lives
in aborts the export (fail-loud, same rule as scripts/okf_lint.py).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from okf_common import iter_concept_files, load_concept, parse_frontmatter

BUNDLE_ROOT = Path(__file__).resolve().parent.parent
TREES = {"system": False, "_lilith_safe": True}


def _git_revision() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(BUNDLE_ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def _okf_version() -> str:
    fm, _ = parse_frontmatter((BUNDLE_ROOT / "index.md").read_text(encoding="utf-8"))
    return str(fm.get("okf_version", "unknown"))


def export(tree: str) -> str:
    root = BUNDLE_ROOT / tree
    if not root.is_dir():
        raise SystemExit(f"tree not found: {root}")
    expected_safe = TREES[tree]

    parts = [
        f"# MAGI knowledge digest — {tree}/",
        "",
        f"* source: `dogmaai/magi-knowledge` @ `{_git_revision()}`",
        f"* okf_version: `{_okf_version()}`",
        f"* lilith_safe: `{str(expected_safe).lower()}`",
        "",
        "Generated by `scripts/okf_export.py`. The repository is the source of",
        "truth — regenerate rather than editing this digest.",
        "",
    ]

    parts += [
        "---",
        "",
        "## How to read this digest (OKF v0.1)",
        "",
        "This is a flattened cache of one directory-tree Markdown bundle in the",
        "Open Knowledge Format (OKF) v0.1. The repository is the source of truth;",
        "regenerate the digest rather than editing it.",
        "Each concept document is Markdown with a flat YAML frontmatter block",
        "delimited by `---` lines, followed by the document body.",
        "`index.md`, `log.md`, and `README.md` are reserved filenames, not concepts.",
        "A concept ID is the bundle-root-relative path with the `.md` suffix removed.",
        "In this digest, each concept appears under a `## <concept_id>` heading.",
        "The italic line immediately below that heading contains the document's",
        "frontmatter, except for `lilith_safe`; the document body follows it.",
        "Only one tree is flattened per digest, and its safety boundary is checked",
        "during export. OKF specification:",
        "https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md",
        "",
    ]

    index = root / "index.md"
    if index.is_file():
        if tree == "system":
            # Only the bundle root index.md carries frontmatter (OKF rule).
            _, bundle_index = parse_frontmatter(
                (BUNDLE_ROOT / "index.md").read_text(encoding="utf-8")
            )
            parts += [
                "---",
                "",
                "## OKF bundle overview",
                "",
                bundle_index.strip(),
                "",
            ]
        parts += [
            "---",
            "",
            f"## {tree}/index.md",
            "",
            index.read_text(encoding="utf-8").strip(),
            "",
        ]

    for path in sorted(iter_concept_files(root)):
        concept = load_concept(BUNDLE_ROOT, path)
        flag = concept.frontmatter.get("lilith_safe")
        if flag is not expected_safe:
            raise SystemExit(
                f"{concept.concept_id}: lilith_safe={flag!r} contradicts tree "
                f"{tree}/ (expected {expected_safe}) — refusing to export"
            )
        meta = ", ".join(
            f"{k}: {v}" for k, v in concept.frontmatter.items() if k != "lilith_safe"
        )
        parts += ["---", "", f"## {concept.concept_id}", ""]
        if meta:
            parts += [f"*{meta}*", ""]
        parts += [concept.body.strip(), ""]

    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tree", choices=sorted(TREES), default="system")
    ap.add_argument("-o", "--output", help="write to this file instead of stdout")
    args = ap.parse_args()

    digest = export(args.tree)
    if args.output:
        Path(args.output).write_text(digest, encoding="utf-8")
        print(
            f"wrote {len(digest)} chars to {args.output}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(digest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
